---
paginate: 5
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks, strikethrough, superscript]

custom:
  title: Mark Lodato's blog
  url: http://marklodato.github.io
  author_name: Mark Lodato
  author_email: lodatom@gmail.com
  analytics_id: UA-13167645-1

gems:
  - jekyll-sitemap
