---
paginate: 5
markdown: kramdown
redcarpet:
  extensions: [fenced_code_blocks, strikethrough, superscript]

custom:
  title: Mark Lodato's blog
  url: https://marklodato.github.io
  author_name: Mark Lodato
  author_email: lodatom@gmail.com
  analytics_id: UA-13167645-1

plugins:
  - jekyll-paginate
  - jekyll-sitemap
